### ISSUE TITLE
Add afetch from 13-CF/afetch

### ISSUE THREAD

**Issue by i3d** [beucismis/awesome-fetch#1]
C based fetch tool.

**Comment by beucismis** [comment]
Can you send a PR? See [contribution guidelines](https://github.com/beucismis/awesome-fetch/blob/main/CONTRIBUTING.md).

**Comment by beucismis** [comment]
Can you send a PR? See [contribution guidelines](https://github.com/beucismis/awesome-fetch/blob/main/CONTRIBUTING.md).

**Comment by beucismis** [comment]
Commit https://github.com/beucismis/awesome-fetch/commit/739a5a100e2d8d58e34b2793ffbf13350e4befea
