### ISSUE TITLE
Add inxi

### ISSUE THREAD

**Issue by aero** [beucismis/awesome-fetch#35]
Name: inxi
Language: Perl
URL: https://github.com/smxi/inxi
Description: inxi is a full featured CLI system information tool. It is available in most Linux distribution repositories, and does its best to support the BSDs.

**Comment by beucismis** [comment]
I like it. Can you send a PR?
![2022-08-23T12:59:41,218376133+03:00](https://user-images.githubusercontent.com/40023234/186131115-e01407ce-4be8-4e43-92cd-9ce6c19ea67e.png)
