### ISSUE TITLE
Add stupidfetch

### ISSUE THREAD

**Issue by 000rosiu** [beucismis/awesome-fetch#38]
Name: Sstupidfetch
Language: Bash
URL: https://github.com/000rosiu/stupidfetch/
Description: Like neofetch, but without colors,without distro logos and installer. Fix it yourself, too easy to use ...

**Comment by beucismis** [comment]
Can you send a PR? See [contribution guidelines](https://github.com/beucismis/awesome-fetch/blob/main/CONTRIBUTING.md).

**Comment by beucismis** [comment]
Commit: [8d5b014](https://github.com/beucismis/awesome-fetch/commit/8d5b014d1f26998108444d5398e1c089a78be6d5)
